#!/bin/bash

version="6.6"
depends=("pkgconf")

install() {
    if [ ! -f ncurses-$version.tar.gz ]; then
        wget https://ftp.gnu.org/gnu/ncurses/ncurses-$version.tar.gz
    fi
    rm -rf ncurses/
    mkdir -p ncurses/
    tar -xf ncurses-$version.tar.gz -C ncurses --strip-components=1
    cd ncurses/
    ./configure --prefix=/usr --mandir=/usr/share/man --with-shared --without-debug --enable-widec --enable-pc-files --with-pkg-config-libdir=/usr/lib/pkgconfig --with-termlib
    make
    make install
    ln -sfv /lib/libtinfow.so /lib/libtinfo.so
}

remove() {
    cd ncurses/
    make uninstall
    rm /lib/libtinfo.so
}
