#!/bin/bash

version="0.23.3"
depends=("")

install() {
    rm -f $version.tar.gz
    wget https://github.com/rockdaboot/libpsl/archive/refs/tags/$version.tar.gz
    rm -rf libpsl/
    mkdir -p libpsl/
    tar -xf $version.tar.gz -C libpsl --strip-components=1
    cd libpsl/
    ./autogen.sh
    ./configure --prefix=/usr
    wget -O list/public_suffix_list.dat https://publicsuffix.org/list/public_suffix_list.dat
    make
    make install
}

remove() {
    cd libpsl/
    make uninstall
}
