#!/bin/sh

depends=("cmake-bin")

install() {
    if [ ! -f 7.1.0.tar.gz ]; then
        wget https://github.com/Jamesbarford/holyc-lang/archive/refs/tags/v0.0.15-beta.tar.gz
    fi
    tar -xf v0.0.15-beta.tar.gz
    cd holyc-lang-0.0.15-beta/
    make $MAKEOPTS
    make install $MAKEOPTS
}

remove() {
    cd holyc-lang-0.0.15-beta/
    make uninstall $MAKEOPTS
}
