#!/bin/bash

version="1.4.7"
depends=("cmake-bin||cmake")

install() {
    if [ ! -f v$version.tar.gz ]; then
        wget https://github.com/aristocratos/btop/archive/refs/tags/v$version.tar.gz
    fi
    mkdir -p btop/
    tar -xf v$version.tar.gz -C btop --strip-components=1
    cd btop/
    make
    make install
}

remove() {
    cd btop/
    make uninstall
}
