#!/bin/bash

version="1.4.7"
depends=("cmake-bin||cmake" "gcc" "glibc" "tar")

install() {
    rm -f v$version.tar.gz
    wget https://github.com/aristocratos/btop/archive/refs/tags/v$version.tar.gz
    rm -rf btop/
    mkdir -p btop/
    tar -xf v$version.tar.gz -C btop --strip-components=1
    cd btop/
    make prefix=/usr
    make install prefix=/usr
}

remove() {
    cd btop/
    make uninstall prefix=/usr
}
