#!/bin/bash

version="2.10.0"
depends=("gcc" "glibc" "make")

install() {
    rm -f kbd-$version.tar.xz
    wget https://www.kernel.org/pub/linux/utils/kbd/kbd-$version.tar.xz
    rm -rf kbd/
    mkdir -p kbd/
    tar -xf kbd-$version.tar.xz -C kbd --strip-components=1
    cd kbd/

    find . -type f \( -name "Makefile*" -o -name "*.sh" \) -exec sed -i 's/ln -s -r/ln -s/g; s/ln -r -s/ln -s/g' {} +

    ./configure \
        --prefix=/usr \
        --disable-vlock

    make
    make install
}

remove() {
    cd kbd/
    make uninstall
}
