#!/bin/bash

version="0.26"
depends=("bash")

install() {
    rm -f gettext-$version.tar.xz
    wget https://ftp.gnu.org/gnu/gettext/gettext-$version.tar.xz
    rm -rf gettext/
    mkdir -p gettext/
    tar -xf gettext-$version.tar.xz -C gettext --strip-components=1
    cd gettext/
	gl_cv_header_working_uchar_h=yes ./configure \
	    --prefix=/usr \
	    --disable-java \
	    --disable-native-java \
    CFLAGS="${CFLAGS} -Wno-error -D_GNU_SOURCE"
    make
    make install
}

remove() {
    cd gettext/
    make uninstall
}
