#!/bin/bash

version="0.26"
depends=("bash")

install() {
    rm -f gettext-$version.tar.xz
    wget https://ftp.gnu.org/gnu/gettext/gettext-$version.tar.xz
    rm -rf gettext/
    mkdir -p gettext/
    tar -xf gettext-$version.tar.xz -C gettext --strip-components=1
    cd gettext/

    ac_cv_header_uchar_h=no \
    gl_cv_header_working_uchar_h=no \
    ./configure \
        --prefix=/usr \
        --disable-java \
        --disable-native-java \
        CFLAGS="${CFLAGS} -D_GNU_SOURCE -Wno-error" \
        CXXFLAGS="${CXXFLAGS} -D_GNU_SOURCE -Wno-error"

    make -j$(nproc)
    make install
}

remove() {
    cd gettext/
    make uninstall
}
