#!/bin/sh

depends=("")

install() {
    if [ ! -f release.tar.gz ]; then
        wget https://github.com/Nick-cpp/wefetch/archive/refs/tags/release.tar.gz
    fi
    tar -xf release.tar.gz
    cd wefetch-release/
    gcc wefetch.c -o wefetch
    cp wefetch /usr/bin/
    mkdir -p /usr/share/wefetch/
    cp -rf logos/ /usr/share/wefetch/
}

remove() {
    rm -f /usr/bin/wefetch
    rm -rf /usr/share/wefetch/
}
