#!/bin/bash

version="2.2"
depends=("bash")

install() {
    if [ ! -f 2.2.tar.gz ]; then
        wget https://github.com/dylanaraps/fff/archive/refs/tags/2.2.tar.gz
    fi
    mkdir -p fff/
    tar -xf 2.2.tar.gz -C fff --strip-components=1
    cd fff/
    make install
}

remove() {
    cd fff/
    make uninstall
}
