#!/bin/sh

version="7.1.0"
depends=("bash")

install() {
    if [ ! -f 7.1.0.tar.gz ]; then
        wget https://github.com/dylanaraps/neofetch/archive/refs/tags/7.1.0.tar.gz
    fi
    mkdir -p neofetch
    tar -xf 7.1.0.tar.gz -C neofetch --strip-components=1
    cd neofetch/
    make install
}

remove() {
    cd neofetch/
    make uninstall
}
