#!/bin/sh

depends=("bash")

install() {
    if [ ! -f 7.1.0.tar.gz ]; then
        wget https://github.com/dylanaraps/neofetch/archive/refs/tags/7.1.0.tar.gz
    fi
    tar -xf 7.1.0.tar.gz
    cd neofetch-7.1.0/
    make install $MAKEOPTS
}

remove() {
    cd neofetch-7.1.0/
    make uninstall $MAKEOPTS
}
