#!/bin/sh

depends=("bash" "tar")

install() {
    wget https://github.com/dylanaraps/neofetch/archive/refs/tags/7.1.0.tar.gz
    tar -xf 7.1.0.tar.gz
    cd neofetch-7.1.0/
    make install
}

remove() {
    cd neofetch-7.1.0/
    make uninstall
}
