#!/bin/bash

version="1.31.3"
depends=("make" "gcc" "glibc" "tar" "xz-utils" "libevdev" "mtdev" "eudev")

install() {
    rm -f libinput-$version.tar.gz
    wget https://gitlab.freedesktop.org/libinput/libinput/-/archive/$version/libinput-$version.tar.gz
    rm -rf libinput/
    mkdir -p libinput/
    tar -xf libinput-$version.tar.gz -C libinput --strip-components=1
    cd libinput/
	mkdir build
	cd build
	
	meson setup ..              \
	      --prefix=/usr         \
	      --buildtype=release   \
	      -D debug-gui=false    \
	      -D tests=false        \
	      -D libwacom=false     \
	      -D udev-dir=/usr/lib/udev
	ninja
    ninja install
}

remove() {
    cd libinput/
    ninja -C build uninstall
}
