#!/bin/bash

version="2.8.2"
depends=("")

install() {
    if [ ! -f expat-2.8.2.tar.xz ]; then
        wget https://github.com/libexpat/libexpat/releases/download/R_2_8_2/expat-2.8.2.tar.xz
    fi
    mkdir -p expat/
    tar -xf expat-2.8.2.tar.xz -C expat --strip-components=1
    cd expat/
    ./configure --prefix=/usr
    make
    make install
}

remove() {
    cd expat/
    make uninstall
}
