#!/bin/bash

version="39"
depends=("")

install() {
    if [ ! -f $version.tar.gz ]; then
        wget https://github.com/rhboot/efivar/archive/refs/tags/$version.tar.gz
    fi
    rm -rf efivar/
    mkdir -p efivar/
    tar -xf $version.tar.gz -C efivar --strip-components=1
    cd efivar/
	make CFLAGS="-Wno-error" MANDOC=true
	make install MANDOC=true
}

remove() {
    cd efivar/
    make uninstall MANDOC=true
}
