#!/bin/bash

version="0.6.0"
depends=("bash")

install() {
    wget https://github.com/dylanaraps/pfetch/archive/refs/tags/0.6.0.tar.gz
    rm -rf pfetch/
    mkdir -p pfetch/
    tar -xf 0.6.0.tar.gz -C pfetch --strip-components=1
    cd pfetch/
    cp pfetch /usr/bin/
}

remove() {
    rm -f /usr/bin/pfetch
}
