#!/bin/sh

version="3.8.2"
depends=("")

install() {
    if [ ! -f bison-3.8.2.tar.xz ]; then
        wget https://ftp.gnu.org/gnu/bison/bison-3.8.2.tar.gz
    fi
    mkdir -p bison/
    tar -xf bison-3.8.2.tar.gz -C bison --strip-components=1
    cd bison/
    ./configure --prefix=/usr
    make $MAKEOPTS
    make install $MAKEOPTS
}

remove() {
    cd bison/
    make uninstall $MAKEOPTS
}
