#!/bin/bash

version="3.1"
depends=("bash")

install() {
    if [ ! -f $version.tar.gz ]; then
        wget https://github.com/Nick-cpp/mspm/archive/refs/tags/$version.tar.gz
    fi
    rm -rf mspm/
    mkdir -p mspm/
    tar -xf $version.tar.gz -C mspm/ --strip-components=1
    cd mspm/
    chmod +x mspm
    cp mspm /usr/bin/
}

remove() {
    rm -f /usr/bin/mspm
}
