#!/bin/bash

version="4.2"
depends=("bash" "tar" "coreutils" "wget")

install() {
    rm -f $version.tar.gz
    wget https://github.com/Nick-cpp/mspm/archive/refs/tags/$version.tar.gz
    rm -rf mspm/
    mkdir -p mspm/
    tar -xf $version.tar.gz -C mspm/ --strip-components=1
    cd mspm/
    chmod +x mspm
    cp mspm /usr/bin/
}

remove() {
    rm -f /usr/bin/mspm
}
