#!/bin/bash

version="5.4.1"
depends=("")

install() {
    wget https://ftp.gnu.org/gnu/gawk/gawk-$version.tar.gz
    rm -rf gawk/
    mkdir -p gawk/
    tar -xf gawk-$version.tar.gz -C gawk --strip-components=1
    cd gawk/
    ./configure --prefix=/usr --sysconfdir=/etc
    make
    make install
}

remove() {
    cd gawk/
    make uninstall
}
