#!/bin/bash

version="4.10"
depends=("make" "gcc" "glibc" "tar" "gzip")

install() {
    rm -f sed-$version.tar.gz
    wget https://ftp.gnu.org/gnu/sed/sed-$version.tar.gz
    rm -rf sed/
    mkdir -p sed/
    tar -xf sed-$version.tar.gz -C sed --strip-components=1
    cd sed/
    ./configure --without-selinux --prefix=/usr
    make
    make install
}

remove() {
    cd sed/
    make uninstall
}
