#!/bin/bash

version="9.12"
depends=("make" "gcc" "glibc" "tar" "gzip")

install() {
    rm -f coreutils-$version.tar.gz
    wget https://ftp.gnu.org/gnu/coreutils/coreutils-$version.tar.gz
    rm -rf coreutils/
    mkdir -p coreutils/
    tar -xf coreutils-$version.tar.gz -C coreutils --strip-components=1
    cd coreutils/
    mkdir build/
    cd build/
    ../configure --prefix=/usr --without-selinux --disable-libcap
    make
    make install
}

remove() {
    cd coreutils/
    cd build/
    make uninstall
}
