#!/bin/bash

version="4.4.3"
depends=("")

install() {
    if [ ! -f v$version.tar.gz ]; then
        wget https://github.com/Kitware/CMake/archive/refs/tags/v$version.tar.gz
    fi
    rm -rf cmake/
    mkdir -p cmake/
    tar -xf v$version.tar.gz -C cmake --strip-components=1
    cd cmake/
    ./configure --prefix=/usr --docdir=share --mandir=share
    make
    make install
}

remove() {
    cd cmake/
    make uninstall
}
