#!/bin/bash

version="1.3"
depends=("bash")

install() {
    if [ ! -f $version.tar.gz ]; then
        wget https://github.com/Nick-cpp/nfetch/archive/refs/tags/$version.tar.gz
    fi
    rm -rf nfetch
    mkdir -p nfetch/
    tar -xf $version.tar.gz -C nfetch --strip-components=1
    cd nfetch/
    chmod +x nfetch
    cp nfetch /usr/bin/
}

remove() {
    rm /usr/bin/nfetch
}
