#!/bin/sh

version="1.19"
depends=("")

install() {
    if [ ! -f popt-1.19.tar.gz ]; then
        wget https://ftp.osuosl.org/pub/rpm/popt/releases/popt-1.x/popt-1.19.tar.gz
    fi
    mkdir -p popt/
    tar -xf popt-1.19.tar.gz -C popt --strip-components=1
    cd popt/
    ./configure --prefix=/usr --disable-static
    make
    make install
}

remove() {
    cd popt/
    make uninstall
}
