#!/bin/sh

version="5.3.0"
depends=("ncurses")

install() {
    if [ ! -f bash-5.3.tar.gz ]; then
        wget https://ftp.gnu.org/gnu/bash/bash-5.3.tar.gz
    fi
    mkdir -p bash/
    tar -xf bash-5.3.tar.gz -C bash --strip-components=1
    cd bash/
    ./configure --sysconfdir=/etc --prefix=/usr --libdir=/usr/lib --without-bash-malloc
    make
    make install
}

remove() {
    cd bash/
    make uninstall
}
