#!/bin/bash

version="1.3.2"
depends=("")

install() {
    if [ ! -f zlib-1.3.2.tar.gz ]; then
        wget https://github.com/madler/zlib/releases/download/v1.3.2/zlib-1.3.2.tar.gz
    fi
    mkdir -p zlib/
    tar -xf zlib-1.3.2.tar.gz -C zlib --strip-components=1
    cd zlib/
    ./configure --prefix=/usr
    make
    make install
}

remove() {
    cd zlib/
    make uninstall
}
